/* eslint-disable @typescript-eslint/no-unused-vars */
import { CATEGORIES, BRANDS, TAGS } from './catalogs'

export const PRODUCTS = [
    {
        id: '000001',
        title: 'Prestige Platina Popular Stainless Steel Gas and Induction Compatible Casserole with Glass Lid',
        brand: BRANDS.Prestige,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B09F3DRD1M',
        image: '000001.png',
    },
    {
        id: '000002',
        title: 'Non Stick Deep Frying Pan, Granite Kadai with Lid, Induction Wok, Saute Pan, Biriyani Pot',
        brand: BRANDS.Carote,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B09V7LC2DY',
        image: '000002.png',
    },
    {
        id: '000003',
        title: 'Bergner Argent Triply Stainless Steel Sautepan/ Deep Frypan with Stainless Steel Lid, 26 cm, 3.1 Litres, Induction Base, Silver, Gas Ready',
        brand: BRANDS.Bergner,
        categories: [CATEGORIES.POTS_PANS],
        tags: [TAGS.frypan, TAGS.frying],
        targetLink: 'https://www.amazon.in/dp/B00LP7FV9W',
        image: '000003.png',
    },
    {
        id: '000004',
        title: 'Hawkins Stainless Steel Tpan 1.5L with Glass lid',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [TAGS.tpan, TAGS.glasslid],
        targetLink: 'https://www.amazon.in/dp/B079M2PDLL',
        image: '000004.png',
    },
    {
        id: '000005',
        title: 'Hawkins 1 Litre Tpan, Stainless Steel Tea Pan, Induction Sauce Pan, Chai Pan, Small Pan, Silver',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [TAGS.tpan],
        targetLink: 'https://www.amazon.in/dp/B07TCQ2RG7',
        image: '000005.png',
    },
    {
        id: '000006',
        title: 'Futura 3 Litre Cook n Serve Stewpot, Non Stick Pot with Glass Lid, Cooking Pot with Lid, Black',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00JFUD8J6',
        image: '000006.png',
    },
    {
        id: '000007',
        title: 'Hawkins Futura 3 Litre Cook n Serve Bowl, Hard Anodised Saucepan with Hard Anodised Lid, Induction Pan, Sauce Pan for Cooking and Serving, Black (IACB30) (Aluminium)',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00JFUCAH2',
        image: '000007.png',
    },
    {
        id: '000008',
        title: 'Futura 3.25 Litre Curry Pan, Non Stick Saute Pan with Glass Lid, Deep Pan for Frying, Black',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00EVQYLOU',
        image: '000008.png',
    },
    {
        id: '000009',
        title: 'Borosil Stainless Steel Handi Casserole with Lid, Impact Bonded Tri-Ply Bottom, 2.2 L, Silver',
        brand: BRANDS.Borosil,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07RDJ6ZGD',
        image: '000009.png',
    },
    {
        id: '0000010',
        title: 'Amazon Brand - Solimo Stainless Steel T Pan with Glass Lid & Induction Base, 1.5 Litre',
        brand: BRANDS.Amazon_Solimo,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07P7X94NP',
        image: '0000010.png',
    },
    {
        id: '0000011',
        title: 'Prestige Platina Popular Stainless Steel Gas and Induction Compatible Fry Pan',
        brand: '',
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B09F2KTLPX',
        image: '0000011.png',
    },
    {
        id: '0000012',
        title: 'Amazon Brand - Solimo Stainless Steel Saucepan with Glass Lid, Induction Base',
        brand: BRANDS.Amazon_Solimo,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07P5TXSWJ',
        image: '0000012.png',
    },
    {
        id: '0000013',
        title: 'Hawkins Futura 26 cm Frying Pan, Non Stick Fry Pan with Glass Lid, Frypan, Black',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00EVQYIQQ',
        image: '0000013.png',
    },
    {
        id: '0000014',
        title: 'Cook n Serve Handi, Triply Stainless Steel Handi with Glass Lid, Induction Sauce Pan, Biryani Handi, Saucepan, Silver',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B08FS18MPK',
        image: '0000014.png',
    },
    {
        id: '0000015',
        title: 'Amazon Brand - Solimo Stainless Steel Sautee Pan with Lid, 24 cm, Silver',
        brand: BRANDS.Amazon_Solimo,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07MWGLWF3',
        image: '0000015.png',
    },
    {
        id: '0000016',
        title: 'Tri-Ply Stainless Steel Tope with Steel Lid',
        brand: BRANDS.Amazon_Solimo,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07P923CC7',
        image: '0000016.png',
    },
    {
        id: '0000017',
        title: 'Hard Anodized Saucepan with Bakelite Handle - 1.5 litres (28cm, 3mm thickness), Aluminium',
        brand: BRANDS.Amazon_Solimo,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07P5SX4F1',
        image: '0000017.png',
    },
    {
        id: '0000018',
        title: 'Futura Hard Anodised Cook-n-Serve Bowl 5 L, 23 cm, 4.06 mm, Aluminium, Black',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B0096DS2QQ',
        image: '0000018.png',
    },
]
