import { CATEGORIES, BRANDS } from './catalogs'

export const PRODUCTS = [
    {
        id: '00001',
        title: 'Prestige Platina Popular Stainless Steel Gas and Induction Compatible Casserole with Glass Lid, 200 mm, 3 Litre',
        brand: BRANDS.Prestige,
        categories: [CATEGORIES.NON_STICK_COOKWARE, CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B09F3DRD1M',
        thumbnail: 'cold_pressed_oil.png',
    },
    {
        id: '00002',
        title: 'Futura Stir-Fry WOK 3 Litre with Induction Base without lid',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00NTZB156',
        thumbnail: 'cold_pressed_oil.png',
    },
    {
        id: '00003',
        title: 'Prestige Platina Popular Stainless Steel Gas and Induction Compatible Casserole with Glass Lid, 200 mm, 3 Litre',
        brand: BRANDS.Prestige,
        categories: [CATEGORIES.NON_STICK_COOKWARE, CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B09F3DRD1M',
        thumbnail: 'cold_pressed_oil.png',
    },
    {
        id: '00004',
        title: 'Futura Stir-Fry WOK 3 Litre with Induction Base without lid',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00NTZB156',
        thumbnail: 'cold_pressed_oil.png',
    },
    {
        id: '00005',
        title: 'Prestige Platina Popular Stainless Steel Gas and Induction Compatible Casserole with Glass Lid, 200 mm, 3 Litre',
        brand: BRANDS.Prestige,
        categories: [CATEGORIES.NON_STICK_COOKWARE, CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B09F3DRD1M',
        thumbnail: 'cold_pressed_oil.png',
    },
    {
        id: '00006',
        title: 'Futura Stir-Fry WOK 3 Litre with Induction Base without lid',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00NTZB156',
        thumbnail: 'cold_pressed_oil.png',
    },
    {
        id: '00007',
        title: 'Prestige Platina Popular Stainless Steel Gas and Induction Compatible Casserole with Glass Lid, 200 mm, 3 Litre',
        brand: BRANDS.Prestige,
        categories: [CATEGORIES.NON_STICK_COOKWARE, CATEGORIES.TAWA_KADAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B09F3DRD1M',
        thumbnail: 'cold_pressed_oil.png',
    },
    {
        id: '00008',
        title: 'Futura Stir-Fry WOK 3 Litre with Induction Base without lid',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00NTZB156',
        thumbnail: 'cold_pressed_oil.png',
    },
    {
        id: '00009',
        title: 'Prestige Platina Popular Stainless Steel Gas and Induction Compatible Casserole with Glass Lid, 200 mm, 3 Litre',
        brand: BRANDS.Prestige,
        categories: [CATEGORIES.NON_STICK_COOKWARE, CATEGORIES.CUTLERIES],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B09F3DRD1M',
        thumbnail: 'cold_pressed_oil.png',
    },
    {
        id: '00010',
        title: 'Futura Stir-Fry WOK 3 Litre with Induction Base without lid',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00NTZB156',
        thumbnail: 'cold_pressed_oil.png',
    },
    {
        id: '00011',
        title: 'Prestige Platina Popular Stainless Steel Gas and Induction Compatible Casserole with Glass Lid, 200 mm, 3 Litre',
        brand: BRANDS.Prestige,
        categories: [CATEGORIES.NON_STICK_COOKWARE, CATEGORIES.CUTLERIES],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B09F3DRD1M',
        thumbnail: 'cold_pressed_oil.png',
    },
    {
        id: '00012',
        title: 'Futura Stir-Fry WOK 3 Litre with Induction Base without lid',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00NTZB156',
        thumbnail: 'cold_pressed_oil.png',
    },
]
