/* eslint-disable @typescript-eslint/no-unused-vars */
import { CATEGORIES, BRANDS, TAGS } from './catalogs'

export const PRODUCTS = [
    {
        id: '000001',
        title: 'Prestige Platina Popular Stainless Steel Gas and Induction Compatible Casserole with Glass Lid',
        brand: BRANDS.Prestige,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B09F3DRD1M',
        image: '000001.png',
    },
    {
        id: '000002',
        title: 'Non Stick Deep Frying Pan, Granite Kadai with Lid, Induction Wok, Saute Pan, Biriyani Pot',
        brand: BRANDS.Carote,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B09V7LC2DY',
        image: '000002.png',
    },
    {
        id: '000003',
        title: 'Bergner Argent Triply Stainless Steel Sautepan/ Deep Frypan with Stainless Steel Lid, 26 cm, 3.1 Litres, Induction Base, Silver, Gas Ready',
        brand: BRANDS.Bergner,
        categories: [CATEGORIES.POTS_PANS],
        tags: [TAGS.frypan, TAGS.frying],
        targetLink: 'https://www.amazon.in/dp/B00LP7FV9W',
        image: '000003.png',
    },
    {
        id: '000004',
        title: 'Hawkins Stainless Steel Tpan 1.5L with Glass lid',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [TAGS.tpan, TAGS.glasslid],
        targetLink: 'https://www.amazon.in/dp/B079M2PDLL',
        image: '000004.png',
    },
    {
        id: '000005',
        title: 'Hawkins 1 Litre Tpan, Stainless Steel Tea Pan, Induction Sauce Pan, Chai Pan, Small Pan, Silver',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [TAGS.tpan],
        targetLink: 'https://www.amazon.in/dp/B07TCQ2RG7',
        image: '000005.png',
    },
    {
        id: '000006',
        title: 'Futura 3 Litre Cook n Serve Stewpot, Non Stick Pot with Glass Lid, Cooking Pot with Lid, Black',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00JFUD8J6',
        image: '000006.png',
    },
    {
        id: '000007',
        title: 'Hawkins Futura 3 Litre Cook n Serve Bowl, Hard Anodised Saucepan with Hard Anodised Lid, Induction Pan, Sauce Pan for Cooking and Serving, Black (IACB30) (Aluminium)',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00JFUCAH2',
        image: '000007.png',
    },
    {
        id: '000008',
        title: 'Futura 3.25 Litre Curry Pan, Non Stick Saute Pan with Glass Lid, Deep Pan for Frying, Black',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00EVQYLOU',
        image: '000008.png',
    },
    {
        id: '000009',
        title: 'Borosil Stainless Steel Handi Casserole with Lid, Impact Bonded Tri-Ply Bottom, 2.2 L, Silver',
        brand: BRANDS.Borosil,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07RDJ6ZGD',
        image: '000009.png',
    },
    {
        id: '0000010',
        title: 'Amazon Brand - Solimo Stainless Steel T Pan with Glass Lid & Induction Base, 1.5 Litre',
        brand: BRANDS.Amazon_Solimo,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07P7X94NP',
        image: '0000010.png',
    },
    {
        id: '0000011',
        title: 'Prestige Platina Popular Stainless Steel Gas and Induction Compatible Fry Pan',
        brand: '',
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B09F2KTLPX',
        image: '0000011.png',
    },
    {
        id: '0000012',
        title: 'Amazon Brand - Solimo Stainless Steel Saucepan with Glass Lid, Induction Base',
        brand: BRANDS.Amazon_Solimo,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07P5TXSWJ',
        image: '0000012.png',
    },
    {
        id: '0000013',
        title: 'Hawkins Futura 26 cm Frying Pan, Non Stick Fry Pan with Glass Lid, Frypan, Black',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00EVQYIQQ',
        image: '0000013.png',
    },
    {
        id: '0000014',
        title: 'Cook n Serve Handi, Triply Stainless Steel Handi with Glass Lid, Induction Sauce Pan, Biryani Handi, Saucepan, Silver',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B08FS18MPK',
        image: '0000014.png',
    },
    {
        id: '0000015',
        title: 'Amazon Brand - Solimo Stainless Steel Sautee Pan with Lid, 24 cm, Silver',
        brand: BRANDS.Amazon_Solimo,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07MWGLWF3',
        image: '0000015.png',
    },
    {
        id: '0000016',
        title: 'Tri-Ply Stainless Steel Tope with Steel Lid',
        brand: BRANDS.Amazon_Solimo,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07P923CC7',
        image: '0000016.png',
    },
    {
        id: '0000017',
        title: 'Hard Anodized Saucepan with Bakelite Handle - 1.5 litres (28cm, 3mm thickness), Aluminium',
        brand: BRANDS.Amazon_Solimo,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07P5SX4F1',
        image: '0000017.png',
    },
    {
        id: '0000018',
        title: 'Futura Hard Anodised Cook-n-Serve Bowl 5 L, 23 cm, 4.06 mm, Aluminium, Black',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B0096DS2QQ',
        image: '0000018.png',
    },
    {
        id: '0000019',
        title: 'SignoraWare 3500ml Artista Tri-Ply Non-Stick Deep Fry Kadhai 24cm, Induction Compatible Cookware Kadai, Grade 304 Stainless Steel, Food Grade, Dishwasher Safe',
        brand: BRANDS.Signoraware,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B08XW23584',
        image: '0000019.png',
    },
    {
        id: '0000020',
        title: 'Stainless Steel Induction Bottom Kadhai Set size 22 cm, 27 cm (2 pieces, 2 Liters, and 3.6 Liters)',
        brand: BRANDS.Amazon_Solimo,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07PB6BFHX',
        image: '0000020.png',
    },
    {
        id: '0000021',
        title: 'Dosa Tawa Non Stick Pan, Granite Tawa for Roti, Flat Dosa Tava, Induction Roti Tawa, 24cm, White',
        brand: BRANDS.Carote,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B09M6DZY34',
        image: '0000021.png',
    },
    {
        id: '0000023',
        title: 'The Indus Valley Cast Iron Tawa/Tava for Dosa/Roti/Chappati/Naan with Long Handle | 10 Inch, 1.9 kg, Gas & Induction-Friendly | Pre-Seasoned, 100% Toxin-Free, Naturally Non-Stick, Long Lasting',
        brand: BRANDS.The_Indus_Valley,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07JVXC599',
        image: '0000023.png',
    },
    {
        id: '0000024',
        title: 'Hawkins Futura Nonstick Dosa Tava, Diameter 33 cm, Thickness 4.88 mm (Black) ',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B0091X7RVM',
        image: '0000024.png',
    },
    {
        id: '0000025',
        title: 'Rock Tawa Dosa Tawa 12 Inch Pre-Seasoned Cast Iron Skillet, Black',
        brand: BRANDS.Rock_Tawa,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B01M0YZBMM',
        image: '0000025.png',
    },
    {
        id: '0000026',
        title: 'NIRLON Stainless Steel Induction & Gas Compatible Sandwich Bottom Casserole with Glass Lid/Belly Cass, Silver',
        brand: BRANDS.Nirlon,
        categories: [CATEGORIES.POTS_PANS],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B0BTMHKLZL',
        image: '0000026.png',
    },
    {
        id: '0000027',
        title: 'Solimo Tri-ply Stainless Steel Induction Base Kadhai with Steel lid',
        brand: BRANDS.Amazon_Solimo,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B08BM1M3RJ',
        image: '0000027.png',
    },
    {
        id: '0000028',
        title: 'HEMER Juwel Triply Stainless Steel Kadai with Lid - 26 cm – 3.5 litres - Tri ply Kadhai with Customized Dome Shaped Lid - SS Riveted Cast Handle - Induction and Gas Stove Friendly',
        brand: BRANDS.Hemer,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B09VPNJQWJ',
        image: '0000028.png',
    },
    {
        id: '0000029',
        title: 'Milton Pro Cook Triply Stainless Steel Kadhai with Lid',
        brand: BRANDS.Milton,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B08K4B958Y',
        image: '0000029.png',
    },
    {
        id: '0000030',
        title: 'Borosil - Stainless Steel Deep Kadhai with Lid, Impact Bonded Tri-Ply Bottom',
        brand: BRANDS.Borosil,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B07RKV6S22',
        image: '0000030.png',
    },
    {
        id: '0000031',
        title: 'Stahl Triply Stainless Steel Kadai with Lid | Stainless Steel Cookware Tri Ply Kadhai | Gas & Induction Base | Artisan 4326, Dia 26 cm, 3.3 L',
        brand: BRANDS.Stahl,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B011VH3RQE',
        image: '0000031.png',
    },
    {
        id: '0000032',
        title: 'Bergner Argent Tri-Ply Stainless Steel Kadhai with Stainless Steel lid (24 cm, 2.5 Liters, Induction Base, Silver)',
        brand: BRANDS.Bergner,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B00E5D9HAM',
        image: '0000032.png',
    },
    {
        id: '0000033',
        title: 'Hawkins Futura Nonstick Kadhai 2.5 L, 26 cm, 3.25 mm with SS lid (Black)',
        brand: BRANDS.Hawkins,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B003SLDNNO',
        image: '0000033.png',
    },
    {
        id: '0000034',
        title: 'Vinod Platinum Triply Stainless Steel Kadai with Stainless Steel Lid 2.5 litres Capacity (24 cm Diameter) | 24 cm Stainless Steel Kadhai with Lid - Silver (Induction and Gas Stove Friendly)',
        brand: BRANDS.Vinod,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B01NHBV5JY',
        image: '0000034.png',
    },
    {
        id: '0000036',
        title: 'Milton Pro Cook Black Pearl Induction Kadhai, 26 cm / 3.4 Litre (Aluminium)',
        brand: BRANDS.Milton,
        categories: [CATEGORIES.TAWA_KADHAI],
        tags: [],
        targetLink: 'https://www.amazon.in/dp/B08KM88Z9H',
        image: '0000036.png',
    },
]
